### PR TITLE
Kafka simple extractor

### PR DESCRIPTION
**Pull request by akshayn1107**
Simple Extractor which reads and returns bytes from Kafka with no data interpretation.

Code Review: @vikarmic @eogren

### CODE REVIEW

**Comment by vikarmic** [comment]
Seems legit to me.

**Comment by eogren** [comment]
looks good aside from the "written by akshay on 4/25/2015" comments

**Comment by akshayn1107** [comment]
My bad, my IDE adds those stupid comments. That should be fixed now for both PRs. Side note: have we thought about what licensing info we should put on each of the files?

**Comment by eogren** [comment]
I would copy the Apache license (same thing LinkedIn has at the head of
everything) but just stick NerdWallet at the top.

**Comment by eogren** [comment]
but yeah otherwise looks good

**Pull request merged**
