### PR TITLE
Merge linkedin:master

### PR DESCRIPTION
**Pull request by ahollenbach**
Merging in linkedin:master.

We are making NW/gobblin an almost-clone of LI/gobblin in order to continually pull the latest updates from upstream. In order to do so, we are moving all NW-specific code to gobblin-modules.

Please refer to this for seeing our diff vs LinkedIn: https://github.com/linkedin/gobblin/compare/master...NerdWallet:merge_linkedin?expand=1

We're going to have a few files different from master - these are needed to incorporate our modules repo in the build.

### CODE REVIEW

**Comment by ahollenbach** [comment]
Kafka and log ingestion jobs are running successfully on the new system.

**Comment by ahollenbach** [comment]
@akshayn1107 @teasherm Take a look

**Comment by eogren** [comment]
have not reviewed, but - awesome!

On Wed, Jul 29, 2015 at 3:08 PM, Andrew Hollenbach <notifications@github.com

**Comment by teasherm** [comment]
This looks good, lets merge and test in stage with https://github.com/NerdWallet/gobblin-workspace/pull/5 next week

**Pull request merged**
