### PR TITLE
Only return bytes/records written if the writer has been closed

### PR DESCRIPTION
**Pull request by akshayn1107**
@vikarmic @eogren

### CODE REVIEW

**Comment by eogren** [comment]
Code looks fine, but do you have any context why it's needed? Also curious if this will make it harder to monitor the job status since bytesWritten would go from 0 -> 1GB or something

**Comment by akshayn1107** [comment]
@eogren This seems to be gobblin convention. Nothing says we need to follow it, but if you look at their avro writer, the assumption is its closed before either bytes written or records written is called.

**Comment by eogren** [comment]
oh ok. in that case works for me.

**Comment by vikarmic** [comment]
Looks good here.

**Pull request merged**
