### PR TITLE
Fix database connection issue

### PR DESCRIPTION
**Pull request by ahollenbach**
Rather than ping, which is not universal across DBs, attempt a single
reconnect. If this fails, you’ll still fail in the same way, but this
solves timeouts, which will be common with Gobblin running as a service
and the CLI/GUI accessing the DB infrequently.

### CODE REVIEW

**Comment by ahollenbach** [comment]
@jfleong @eogren fix for yesterday's issue

**Comment by eogren** [comment]
lgtm

**Comment by ahollenbach** [comment]
The above "solution" causes a connection pool leak :(

Also, attempting to close the connection if it is invalid (the result of the first `.getConnection()` does not actually release it back into the connection pool. Can't seem to figure out why Gobblin is not letting go of the connections.

**Comment by ahollenbach** [comment]
@eogren removed connection leak for now

**Pull request merged**
